name: Package Application with Pyinstaller
            
on: 
    push:
        paths:
            - 'Dedicated Server Install Guide\auto_add_to_favserver\**\*.py'

    workflow_dispatch:
        paths:
            - 'Dedicated Server Install Guide\auto_add_to_favserver\**'
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          python_ver: '3.9'
          spec: 'Dedicated Server Install Guide\auto_add_to_favserver\add_to_favserver.py'
          requirements: 'Dedicated Server Install Guide\auto_add_to_favserver\requirements.txt'
          upload_exe_with_name: 'AutoAdd2Fav'
          options: --onefile, --name "AutoAdd2Fav", 